name: playwright upload douyin
on:
  schedule:
    - cron: "*/10 * * * *"
  push:
    branches:
      - "master"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "INFO"
        type: choice
        options:
          - INFO
          - DEBUG
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get update
        sudo apt-get install ffmpeg -y
        pip install playwright
        pip install -r requirements.txt
        pip install yt-dlp --upgrade
        sudo timedatectl set-timezone "Asia/Shanghai"
    - name: Ensure browsers are installed
      run: |
        python -m playwright install --with-deps
        python -m playwright install chromium
    - name: main logic
      env:
        GIST_ID: ${{secrets.GIST_ID}}
        GIT_TOKEN: ${{secrets.GIT_TOKEN}}
      run: python dy_upload.py $GIT_TOKEN $GIST_ID --logLevel=${{ inputs.logLevel || 'INFO' }}
